dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - rust: stable
      env: RUSTFLAGS="--cfg finchers_deny_warnings"
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo update
        - cargo test --all-features
        - cargo test -p example-askama
        - cargo fmt -- --check
        - if [[ "${TRAVIS_PULL_REQUEST_BRANCH:-}" = release-* ]]; then cargo publish --dry-run; fi

    - rust: beta
      env: RUSTFLAGS="--cfg finchers_deny_warnings"
      script:
        - cargo update
        - cargo test --all-features
        - cargo test -p example-askama

    - rust: nightly
      script:
        - cargo update
        - cargo test --all-features
        - cargo test -p example-askama

    - rust: stable
      env: DEPLOY_API_DOC
      before_script:
      script:
        - rm -rf target/doc
        - cargo update
        - cargo doc --no-deps --all-features -p askama -p tera -p handlebars -p horrorshow
        - cargo doc --no-deps --all-features
        - rm -f target/doc/.lock
        - echo '<meta http-equiv="refresh" content="0;URL=finchers_template/index.html">' > target/doc/index.html
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers-template
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
