(function() {var implementors = {};
implementors["finchers_template"] = [{text:"impl&lt;CtxT&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"finchers_template/backend/struct.AskamaEngine.html\" title=\"struct finchers_template::backend::AskamaEngine\">AskamaEngine</a>&lt;CtxT&gt;",synthetic:false,types:["finchers_template::backend::askama::AskamaEngine"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"finchers_template/backend/struct.HorrorshowEngine.html\" title=\"struct finchers_template::backend::HorrorshowEngine\">HorrorshowEngine</a>",synthetic:false,types:["finchers_template::backend::horrorshow::HorrorshowEngine"]},];
implementors["handlebars"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"handlebars/struct.Handlebars.html\" title=\"struct handlebars::Handlebars\">Registry</a>",synthetic:false,types:["handlebars::registry::Registry"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"handlebars/struct.StringWriter.html\" title=\"struct handlebars::StringWriter\">StringWriter</a>",synthetic:false,types:["handlebars::support::str::StringWriter"]},];
implementors["horrorshow"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"horrorshow/struct.Error.html\" title=\"struct horrorshow::Error\">Error</a>",synthetic:false,types:["horrorshow::error::Error"]},];
implementors["tera"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tera/struct.Context.html\" title=\"struct tera::Context\">Context</a>",synthetic:false,types:["tera::context::Context"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"tera/struct.Tera.html\" title=\"struct tera::Tera\">Tera</a>",synthetic:false,types:["tera::tera::Tera"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
